//
//  OrderedMultiValueDictionary+Collection.swift
//  ErrorInfo
//
//  Created by Dmitriy Ignatyev on 06/10/2025.
//

extension OrderedMultiValueDictionary: Collection {
  @inlinable
  @inline(__always)
  public var count: Int { _entries.count }
  
  @inlinable
  @inline(__always)
  public var isEmpty: Bool { _entries.isEmpty }
}

extension OrderedMultiValueDictionary: RandomAccessCollection {
  @inlinable
  public var startIndex: Int { _entries.startIndex }
  
  @inlinable
  public var endIndex: Int { _entries.endIndex }
    
  @inlinable
  public subscript(position: Int) -> Element { _entries[position] }
}

extension OrderedMultiValueDictionary {
  /// Returns a Boolean value indicating whether the sequence contains values for a given key that satisfies the given predicate.
  internal func containsValues<E>(forKey key: Key, where predicate: (Value) throws(E) -> Bool) rethrows -> Bool {
    if let allValuesForKeyIndices = _keyToEntryIndices[key] {
      // TODO: performance test
      // may be `switch indexSet case single(let index)` would be faster for single value
      // for multiple values  NonEmptyOrderedIndexSet has autogenerated Iterator, which iterates over `subscript(position:)`
      // which switches enum NonEmptyOrderedIndexSet._storage every time
      try allValuesForKeyIndices.contains(where: { index in
        try predicate(_entries[index].value)
      })
    } else {
      false
    }
  }
}

/*
 TODO:
 1) conform it to DictionaryProtocol for using with Dict merge / addPrefix functions
 2) AllValuesForKeyView ~Escapable | RangeSet instead IndexSet | entries without storing keys
 */
